# -*- coding: utf-8 -*-
"""Jou-Jogo-do-desafio
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1vhRzYFMXK93-jqN99dl3qXZkt9m5BSjN
"""

import random
import json

# ==========================
# CONFIGURAÇÕES GLOBAIS
# ==========================
PONTOS_PARA_VENCER = 50
NOME_ARQUIVO_RANKING = "ranking_jogo.json"


def obter_lista_desafios():
    """Retorna a lista de desafios disponíveis no sistema."""
    return [
        "Cantar uma música por 30 segundos", "Fazer uma imitação engraçada",
        "Contar uma piada", "Dançar por 20 segundos", "Fazer uma mímica",
        "Falar um trava-língua três vezes seguidas", "Inventar uma história curta",
        "Fazer um elogio criativo para alguém", "Equilibrar um objeto por 15 segundos",
        "Fazer uma apresentação engraçada de 30 segundos", "Fazer 10 polichinelos",
        "Falar sem rir por 30 segundos", "Imitar um animal escolher pelo grupo",
        "Fazer uma pose engraçada por 15 segundos", "Falar o alfabeto de trás para frente em 30 segundos",
        "Ficar em um pé só com os olhos fechados por 20 segundos",
        "Desenhar um animal com a mão não dominante em 30 segundos", "Tentar lamber o próprio cotovelo",
        "Falar uma palavra longa de trás para frente (ex: PARALELO)",
        "Fazer uma rima improvisada com o nome de alguém do grupo",
        "Contar de 1 a 20 pulando os números múltiplos de 3", "Imitar uma estátua por 30 segundos sem piscar",
        "Fazer um som de instrumento musical apenas com a boca",
        "Elogiar o time adversário de 3 formas diferentes e rápidas",
        "Segurar o riso enquanto o grupo faz caretas por 20 segundos",
        "Bater palma no ritmo de uma música para o grupo adivinhar",
        "Falar por 30 segundos usando apenas sussurros", "Andar in linha reta de costas olhando para o teto",
        "Fazer uma propaganda engraçada de um objeto que está na sala",
        "Dizer 5 coisas vermelhas que você está vendo agora em 10 segundos",
        "Fazer uma imitação de um robô dançando", "Gesticular como um maestro regendo uma orquestra maluca",
        "Falar uma frase inteira sem mover os lábios", "Contar uma curiosidade bizarra que você sabe",
        "Fazer 5 agachamentos enquanto recita um poema ou música",
        "Imitar um locutor de rádio ou de futebol por 20 segundos",
        "Desenhar um círculo no ar com o pé direito e um quadrado com a mão direita",
        "Ficar sem falar a palavra 'NÃO' por duas rodadas completas",
        "Completar o desafio de olhar fixamente para um adversário sem rir",
        "Dizer 3 palavras que rimem com 'computador' em 5 segundos"
    ]


def salvar_historico(times_finais):
    """Grava o placar final do jogo atual em um arquivo JSON de histórico."""
    try:
        try:
            with open(NOME_ARQUIVO_RANKING, "r", encoding="utf-8") as arquivo:
                historico = json.load(arquivo)
        except (FileNotFoundError, json.JSONDecodeError):
            historico = []

        partida_atual = {nome: dados["pontos"] for nome, dados in times_finais.items()}
        historico.append(partida_atual)

        with open(NOME_ARQUIVO_RANKING, "w", encoding="utf-8") as arquivo:
            json.dump(historico, arquivo, indent=4, ensure_ascii=False)

        print(f"\n💾 Pontuações salvas com sucesso em '{NOME_ARQUIVO_RANKING}'!")
    except Exception as e:
        print(f"\n⚠️ Erro ao salvar as pontuações: {e}")


def cadastrar_times():
    """Gerencia o cadastro dos 3 times e seus respectivos integrantes."""
    times = {}
    print("=" * 50)
    print("🎮 JOGO DO DESAFIO")
    print("=" * 50)

    for numero_time in range(1, 4):
        print(f"\nCadastro do Time {numero_time}")
        nome_time = input("Nome do time: ").strip()

        while not nome_time or nome_time in times:
            nome_time = input("Nome inválido ou já existente. Digite outro: ").strip()

        while True:
            try:
                quantidade = int(input("Quantidade de integrantes (1 a 5): "))
                if 1 <= quantidade <= 5:
                    break
                print("Digite um número entre 1 e 5.")
            except ValueError:
                print("Valor inválido. Digite um número inteiro.")

        integrantes = []
        for i in range(quantidade):
            while True:
                integrante = input(f"Nome do integrante {i+1}: ").strip()
                if integrante:
                    integrantes.append(integrante)
                    break
                print("O nome não pode ser vazio.")

        times[nome_time] = {
            "integrantes": integrantes,
            "pontos": 0
        }
    print("\n✅ Times cadastrados com sucesso!")
    return times


def processar_resultado(times, time_sorteado, participante, pontos):
    """Obtém a resposta do usuário e calcula o impacto na pontuação do time."""
    print("\nResultado:")
    print("1 - Cumpriu o desafio")
    print("2 - Tentou e não conseguiu")
    print("3 - Recusou realizar o desafio")

    while True:
        resultado = input("\nEscolha (1, 2 ou 3): ").strip()
        if resultado in ["1", "2", "3"]:
            break
        print("Opção inválida.")

    if resultado == "1":
        times[time_sorteado]["pontos"] += pontos
        print(f"\n✅ {participante} cumpriu o desafio. {time_sorteado} ganhou {pontos} ponto(s).")
    elif resultado == "2":
        perda = pontos // 2
        times[time_sorteado]["pontos"] = max(0, times[time_sorteado]["pontos"] - perda)
        print(f"\n⚠️ {participante} tentou, mas não conseguiu. {time_sorteado} perdeu {perda} ponto(s).")
    else:
        times[time_sorteado]["pontos"] = max(0, times[time_sorteado]["pontos"] - pontos)
        print(f"\n❌ {participante} recusou o desafio. {time_sorteado} perdeu {pontos} ponto(s).")


def exibir_placar(times):
    """Exibe o placar atual das equipes formatado em tabela."""
    print("\n┌" + "─" * 42 + "┐")
    print(f"│ {'📊 PLACAR ATUAL':^40} │")
    print("├" + "─" * 25 + "┬" + "─" * 16 + "┤")
    for nome, dados in times.items():
        # Corta nomes muito longos para manter o alinhamento da tabela
        nome_formatado = nome[:23] + ".." if len(nome) > 23 else nome
        print(f"│ {nome_formatado:<23} │ {dados['pontos']:>7} pontos │")
    print("└" + "─" * 25 + "┴" + "─" * 16 + "┘")


def verificar_vencedor(times):
    """Avalia se alguma equipe atingiu a meta e retorna o nome do campeão."""
    vencedores_potenciais = [nome for nome, dados in times.items() if dados["pontos"] >= PONTOS_PARA_VENCER]
    if vencedores_potenciais:
        return max(vencedores_potenciais, key=lambda x: times[x]["pontos"])
    return None
# Se houver mais de um acima de 50, ganha quem tiver mais pontos

def executar_jogo():
    """Função principal que coordena o fluxo de rodadas do programa."""
    desafios_disponiveis = obter_lista_desafios()
    times = cadastrar_times()
    rodada = 1
 # Criamos uma lista com os times e embaralhamos para definir a ordem de turnos fixa e justa
    ordem_times = list(times.keys())
    random.shuffle(ordem_times)

    indice_time_atual = 0

    while True:
        print("\n" + "=" * 60)
        print(f"🎲 JOGADA Nº {rodada}")
        print("=" * 60)

                # Seleciona o time da vez de forma circular
        time_sorteado = ordem_times[indice_time_atual]
        participante = random.choice(times[time_sorteado]["integrantes"])

                # Se os desafios acabarem, recarrega a lista original
        if not desafios_disponiveis:
            desafios_disponiveis = obter_lista_desafios()

         # Sorteia um desafio e remove da lista para não repetir
        desafio = random.choice(desafios_disponiveis)
        desafios_disponiveis.remove(desafio)

        pontos = random.randint(1, 6)

        print(f"\n🏳️ Time da vez: {time_sorteado}")
        print(f"👤 Participante selecionado: {participante}")
        print(f"🎯 Desafio: {desafio}")
        print(f"⭐ Pontos valendo: {pontos}")

        processar_resultado(times, time_sorteado, participante, pontos)
        exibir_placar(times)

        vencedor = verificar_vencedor(times)
        if vencedor:
            print("\n" + "🏆" * 15)
            print(f"🏆 O TIME VENCEDOR É: {vencedor}")
            print(f"🏆 Finalizou com {times[vencedor]['pontos']} pontos!")
            print("🏆" * 15)

            salvar_historico(times)
            break

            # Passa para o próximo time na ordem (volta para o 0 quando chega ao fim da lista)
        indice_time_atual = (indice_time_atual + 1) % len(ordem_times)
        rodada += 1

        # Linha corrigida com comando de saída voluntária
        opcao = input("\nPressione ENTER para a próxima jogada ou digite 'sair': ").strip().lower()
        if opcao == "sair":
            print("\nJogo encerrado pelo usuário.")
            salvar_historico(times)
            break


if __name__ == "__main__":
    executar_jogo()
    
